name: Get CHT concepts with scopeNote for Kennisbank

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:  # Manual trigger

jobs:
  run_sparql_query:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run SPARQL query and save as TTL
      run: |
        python scripts/cht_poolparty_kennisbank.py

    - name: Check for changes
      id: git-check
      run: echo ::set-output name=changed::$(if [ -n "$(git status --porcelain)" ]; then echo true; else echo false; fi)

    - name: Commit changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add output.ttl
        git commit -m "Add output.ttl"
        git push
      
    - name: No changes message
      if: steps.git-check.outputs.changed != 'true'
      run: echo "No changes to commit"
