name: 'PoolParty Concepts Backup'

env:
  POOLPARTY_API_ENDPOINT: 'https://digitaalerfgoed.poolparty.biz/PoolParty/api/'
  PROJECT_NAME: '1DE00459-F03C-0001-87E1-19104AD0154A'
  TARGET_FILEPATH: 'cht_backup.trig'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download file with curl
      run: |
        curl -o ${{ github.workspace }}${{ inputs.target-filepath }} -u "${{ secrets.POOLPARTY_USERNAME }}:${{ secrets.POOLPARTY_PASSWORD }}" -H "Content-Type: application/json" -d '{
          "prettyPrint": true,
          "format": "TriG",
          "modules": [ "concepts" ]
        }' ${{ inputs.poolparty-instance-api-endpoint }}projects/${{ inputs.project-name }}/export
        
        exit_code=$?

        if [ $exit_code -ne 0 ]; then
          echo "Curl command failed with exit code $exit_code"
          echo "$response"
          exit $exit_code
        fi
      env:
        TARGET_FILEPATH: ${{ env.TARGET_FILEPATH }}
        POOLPARTY_API_ENDPOINT: ${{ env.POOLPARTY_API_ENDPOINT }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}

    - name: Commit and push
      if: success()
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add ${{ github.workspace }}/${{ env.TARGET_FILEPATH }}
        git commit -m 'Scheduled PoolParty Thesaurus Backup'
        git push
