name: 'PoolParty Concepts Backup'

env:
  POOLPARTY_API_ENDPOINT: 'https://digitaalerfgoed.poolparty.biz/PoolParty/api/'
  PROJECT_NAME: '1DE00459-F03C-0001-87E1-19104AD0154A'
  TARGET_FILEPATH: '/cht_backup.trig'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download file with curl
      run: |
        curl -o ${{ github.workspace }}$TARGET_FILEPATH -u "${{ secrets.POOLPARTY_USERNAME }}:${{ secrets.POOLPARTY_PASSWORD }}" -H "Content-Type: application/json" -d '{
          "prettyPrint": true,
          "format": "TriG",
          "modules": [ "concepts" ]
        }' $POOLPARTY_API_ENDPOINT/projects/$PROJECT_NAME/export

    - name: Commit and push
      if: success()
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add $TARGET_FILEPATH
        git commit -m 'Scheduled PoolParty Thesaurus Backup'
        git push
