name: PoolParty Export Workflow test 2

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'
  push:  # Trigger on every push
    branches:
      - main  # Adjust to your repository's main branch

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file with curl
      run: |
        api_url="https://digitaalerfgoed-test.poolparty.biz/PoolParty/api/projects/caf6168c-9636-4ad8-b6b2-383276bbfb50/export"
        json_payload='{"prettyPrint":true,"format":"TriG","modules":["concepts"]}'
        output_file="test_backup.trig"
        
        echo "API URL: $api_url"
        echo "API Username: $API_USERNAME"
        
        curl -0 -H "Content-Type: application/json" -u "$API_USERNAME:$API_PASSWORD" --data "$json_payload" "$api_url" --output "$output_file"
        
      - name: Upload exported file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: exported-file
        path: ${{ github.workspace }}/test_backup.trig