name: PoolParty Export Workflow

on:
  schedule:
    - cron: '38 9 * * *'  # Runs daily at XXX
  push:  # Trigger on every push
    branches:
      - main  # Adjust to your repository's main branch

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download PoolParty export
      env:
        API_USERNAME: ${{ secrets.POOLPARTY_USERNAME }}
        API_PASSWORD: ${{ secrets.POOLPARTY_PASSWORD }}
      run: |
        api_url="https://digitaalerfgoed.poolparty.biz/PoolParty/api/projects/1DF17ED4-4A38-0001-C6FF-883013B04AD0/export"
        json_payload='{"prettyPrint":true,"format":"TriG","modules":["concepts"]}'
        output_file="test_backup.trig"
        
        echo "API URL: $api_url"
        echo "API Username: $API_USERNAME"
        
        curl -X POST -H "Content-Type: application/json" -u "$API_USERNAME:$API_PASSWORD" --data "$json_payload" "$api_url" --output "$output_file"

      
    - name: Upload exported file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/test_backup.trig
