name: Test Curl Command

on:
  push:
    branches:
      - main  # Adjust to your repository's main branch

jobs:
  test-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test Curl Command
        run: |
          curl --version
          curl -I https://www.example.com  # Replace with an actual URL you want to test
